### ISSUE TITLE
Problem with Dice so Nice

### ISSUE THREAD

**Issue by Damaskian** [fvtt-fria-ligan/vastgrimm-foundry-vtt#1]
I am on Foundry VTT version 10 and with the Vast Grimm system upgraded to 1.0.0.
When I activate the Dice So Nice! module I get that error and the result is not displayed in the chat. If I disable it it works correctly.

![image](https://user-images.githubusercontent.com/70920540/203840295-307242db-1e44-4c63-b08c-aab43fbfcff9.png)

**Comment by mcglincy** [comment]
Thanks for the bug report! Fixed in a new 1.0.1 release.
